apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: demo-gitlab-tls
  namespace: default
spec:
  dnsNames:
  - demo.gitlab.rancheris.in
  issuerRef:
    kind: Issuer
    name: gitlab-issuer
  secretName: demo-gitlab-tls
